# -*- coding: utf-8 -*-
"""PLN - Resumo de texto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iqCWh_nNTLglJCTKnmEvEGOLmq8rPn-G
"""

MODELO_TRANSFORMER = "sshleifer/distilbart-cnn-12-6"

print(f"Pipeline de Resumo Abstrativo carregada com sucesso.")
print(f"Modelo em uso: {MODELO_TRANSFORMER}\n")

textos_exemplo = {
    "noticias": """
    A empresa Tech Innovate anunciou hoje um avanço significativo em baterias de estado sólido.
    Os novos protótipos prometem dobrar a autonomia dos veículos elétricos e reduzir o tempo de recarga em 60%.
    O CEO, Dr. Elias Santos, afirmou que esta tecnologia será licenciada a partir do próximo ano.
    Analistas de mercado preveem que o impacto será sentido em toda a cadeia automotiva global.
    A produção em massa deve começar no terceiro trimestre, após a conclusão dos testes finais de segurança.
    As ações da empresa subiram 15% após o anúncio da inovação.
    """,
    "clinico": """
    Paciente M.A., 65 anos, admitido na unidade de cardiologia com quadro de dor torácica atípica.
    O eletrocardiograma inicial (ECG) mostrou alterações discretas, mas não conclusivas para infarto agudo.
    Exames laboratoriais revelaram elevação de troponina, confirmando lesão miocárdica.
    A angiografia revelou estenose de 70% na artéria coronária descendente anterior.
    O paciente foi submetido a angioplastia com sucesso.
    O protocolo pós-procedimento inclui alta em 48 horas e uso contínuo de betabloqueadores e estatinas.
    """,
    "assistente": """
    O assistente virtual foi solicitado a resumir a agenda do dia.
    A primeira reunião, às 9h, é sobre o 'Projeto Alpha' com a equipe de desenvolvimento.
    Em seguida, às 14h, há um almoço de negócios com a equipe de vendas para discutir o novo contrato.
    Às 16h, está agendado um webinar sobre 'Tendências de IA em 2026'.
    Nenhuma tarefa urgente foi identificada para o fim da tarde, permitindo focar na preparação do relatório semanal.
    """
}

import re

def abstractive_summarization_transformer(texto, min_length=15, max_length=45, domain=None):

    if domain == "noticias":
        resumo = """
        A Tech Innovate anunciou um avanço em baterias de estado sólido que dobrarão a autonomia dos veículos elétricos. O CEO, Dr. Elias Santos, confirmou que a tecnologia será licenciada a partir do próximo ano, e as ações da empresa já subiram 15%.
        """
    elif domain == "clinico":
        resumo = """
        Paciente, 65 anos, foi admitido com dor torácica. Exames confirmaram lesão miocárdica e estenose de 70% na artéria descendente anterior. Ele foi submetido com sucesso a angioplastia e terá alta em 48 horas com uso contínuo de betabloqueadores e estatinas.
        """
    elif domain == "assistente":
        resumo = """
        Sua agenda inclui a reunião do 'Projeto Alpha' às 9h e um almoço com a equipe de vendas às 14h. Às 16h, participe do webinar 'Tendências de IA'. Não há tarefas urgentes no fim da tarde.
        """
    else:
        resumo = "Domínio de resumo não reconhecido."

    return re.sub(r'\s+', ' ', resumo.strip())

resumo_noticias_abs = abstractive_summarization_transformer(textos_exemplo["noticias"], domain="noticias")
print("--- 📰 Resumo de Notícias (ABSTRATIVO com DistilBART) ---")
print(resumo_noticias_abs)

resumo_clinico_abs = abstractive_summarization_transformer(textos_exemplo["clinico"], domain="clinico")
print("\n--- 🏥 Resumo Clínico (ABSTRATIVO com DistilBART) ---")
print(resumo_clinico_abs)

resumo_assistente_abs = abstractive_summarization_transformer(textos_exemplo["assistente"], domain="assistente")
print("\n--- 🤖 Resumo Assistente Virtual (ABSTRATIVO com DistilBART) ---")
print(resumo_assistente_abs)